### ISSUE TITLE
No Preview

### ISSUE THREAD

**Issue by mzed** [alexnj/visual-bikeshed#1]
I just installed this extension on MacOs 14.5, Visual Studio Code 1.93.1 

My file is recognized as a Bikeshed file, but I don't see the icon to open a preview. I don't have a local install of bikeshed.

**Comment by alexnj** [comment]
Are you able to open the preview pane using `CMD+SHIFT+P` and selecting 'Open Bikeshed Preview'? 

If the preview pane is opening, but not a preview isn't rendering — try adjusting the settings of the extension (`visualBikeshed.compilerOption`) to use a URL based compiler.

**Comment by mzed** [comment]
`CMD+SHIFT+P` works. Thanks.
